# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'
use_frameworks!

target 'LinkDemo-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks

source 'https://github.com/CocoaPods/Specs.git'
pod 'Plaid'

end
